<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;

class home extends Controller
{
    public function index()
    {

        return view('welcome')
            ->with('address', DB::table('content_static')->where('ID', 'address')->get())
            ->with('content_about', DB::table('content_static')->where('ID', 'content-about')->get())
            ->with('content_CONSULTATION', DB::table('content_static')->where('ID', 'content-CONSULTATION')->get())
            ->with('content_industry', DB::table('content_static')->where('ID', 'content-industry')->get())
            ->with('content_managed_it_servce', DB::table('content_static')->where('ID', 'content-managed-it-servce')->get())
            ->with('content_SOLUTIONS_DELIVER', DB::table('content_static')->where('ID', 'content-SOLUTIONS_DELIVER')->get())
            ->with('email', DB::table('content_static')->where('ID', 'email')->get())
            ->with('facebook_link', DB::table('content_static')->where('ID', 'facebook-link')->get())
            ->with('featcher_card_1_content', DB::table('content_static')->where('ID', 'featcher-card-1-content')->get())
            ->with('featcher_card_1_image', DB::table('content_static')->where('ID', 'featcher-card-1-image')->get())
            ->with('featcher_card_1_subtitle', DB::table('content_static')->where('ID', 'featcher-card-1-subtitle')->get())
            ->with('featcher_card_1_title', DB::table('content_static')->where('ID', 'featcher-card-1-title')->get())
            ->with('featcher_card_2_content', DB::table('content_static')->where('ID', 'featcher-card-2-content')->get())
            ->with('featcher_card_2_image', DB::table('content_static')->where('ID', 'featcher-card-2-image')->get())
            ->with('featcher_card_2_subtitle', DB::table('content_static')->where('ID', 'featcher-card-2-subtitle')->get())
            ->with('featcher_card_2_title', DB::table('content_static')->where('ID', 'featcher-card-2-title')->get())
            ->with('featcher_card_3_content', DB::table('content_static')->where('ID', 'featcher-card-3-content')->get())
            ->with('featcher_card_3_image', DB::table('content_static')->where('ID', 'featcher-card-3-image')->get())
            ->with('featcher_card_3_subtitle', DB::table('content_static')->where('ID', 'featcher-card-3-subtitle')->get())
            ->with('featcher_card_3_title', DB::table('content_static')->where('ID', 'featcher-card-3-title')->get())
            ->with('featcher_link', DB::table('content_static')->where('ID', 'featcher-link')->get())
            ->with('image_1_industry', DB::table('content_static')->where('ID', 'image-1-industry')->get())
            ->with('image_2_industry', DB::table('content_static')->where('ID', 'image-2-industry')->get())
            ->with('image_3_industry', DB::table('content_static')->where('ID', 'image-3-industry')->get())
            ->with('image_4_industry', DB::table('content_static')->where('ID', 'image-4-industry')->get())
            ->with('image_5_industry', DB::table('content_static')->where('ID', 'image-5-industry')->get())
            ->with('image_6_industry', DB::table('content_static')->where('ID', 'image-6-industry')->get())
            ->with('image_7_industry', DB::table('content_static')->where('ID', 'image-7-industry')->get())
            ->with('image_8_industry', DB::table('content_static')->where('ID', 'image-8-industry')->get())
            ->with('image_managed_it_service', DB::table('content_static')->where('ID', 'image-managed-it-service')->get())
            ->with('linkedin_link', DB::table('content_static')->where('ID', 'linkedin-link')->get())
            ->with('link_OUR_Instagram_SAY', DB::table('content_static')->where('ID', 'link_OUR_Instagram_SAY')->get())
            ->with('link_managed_it_service', DB::table('content_static')->where('ID', 'link-managed-it-service')->get())
            ->with('link_stories', DB::table('content_static')->where('ID', 'link-stories')->get())
            ->with('nav_card_center_content', DB::table('content_static')->where('ID', 'nav-card-center-content')->get())
            ->with('nav_card_center_link', DB::table('content_static')->where('ID', 'nav-card-center-link')->get())
            ->with('nav_card_center_title', DB::table('content_static')->where('ID', 'nav-card-center-title')->get())
            ->with('nav_card_left_content', DB::table('content_static')->where('ID', 'nav-card-left-content')->get())
            ->with('nav_card_left_link', DB::table('content_static')->where('ID', 'nav-card-left-link')->get())
            ->with('nav_card_left_title', DB::table('content_static')->where('ID', 'nav-card-left-title')->get())
            ->with('nav_card_right_content', DB::table('content_static')->where('ID', 'nav-card-right-content')->get())
            ->with('nav_card_right_link', DB::table('content_static')->where('ID', 'nav-card-right-link')->get())
            ->with('nav_card_right_title', DB::table('content_static')->where('ID', 'nav-card-right-title')->get())
            ->with('PALT_WORK_contnet', DB::table('content_static')->where('ID', 'PALT_WORK-contnet')->get())
            ->with('PALT_WORK_image_1', DB::table('content_static')->where('ID', 'PALT_WORK-image-5')->get())
            ->with('PALT_WORK_image_2', DB::table('content_static')->where('ID', 'PALT_WORK-image-5')->get())
            ->with('PALT_WORK_image_3', DB::table('content_static')->where('ID', 'PALT_WORK-image-5')->get())
            ->with('PALT_WORK_image_4', DB::table('content_static')->where('ID', 'PALT_WORK-image-5')->get())
            ->with('PALT_WORK_image_5', DB::table('content_static')->where('ID', 'PALT_WORK-image-5')->get())
            ->with('phone', DB::table('content_static')->where('ID', 'phone')->get())
            ->with('press_1_link', DB::table('content_static')->where('ID', 'press-1-link')->get())
            ->with('press_1_title', DB::table('content_static')->where('ID', 'press-1-title')->get())
            ->with('press_2_link', DB::table('content_static')->where('ID', 'press-2-link')->get())
            ->with('press_2_title', DB::table('content_static')->where('ID', 'press-2-title')->get())
            ->with('SOLUTIONS_DELIVER_content', DB::table('content_static')->where('ID', 'SOLUTIONS_DELIVER-content')->get())
            ->with('stories_card_1_content', DB::table('content_static')->where('ID', 'stories-card-1-content')->get())
            ->with('stories_card_1_title', DB::table('content_static')->where('ID', 'stories-card-1-title')->get())
            ->with('stories_card_2_content', DB::table('content_static')->where('ID', 'stories-card-2-content')->get())
            ->with('stories_card_2_title', DB::table('content_static')->where('ID', 'stories-card-2-title')->get())
            ->with('stories_card_3_content', DB::table('content_static')->where('ID', 'stories-card-3-content')->get())
            ->with('stories_card_3_title', DB::table('content_static')->where('ID', 'stories-card-3-title')->get())
            ->with('stories_card_4_content', DB::table('content_static')->where('ID', 'stories-card-4-content')->get())
            ->with('stories_card_4_title', DB::table('content_static')->where('ID', 'stories-card-4-title')->get())
            ->with('stories_link', DB::table('content_static')->where('ID', 'stories-link')->get())
            ->with('sub_title', DB::table('content_static')->where('ID', 'sub-title')->get())
            ->with('trends_content', DB::table('content_static')->where('ID', 'trends-content')->get())
            ->with('twitter_link', DB::table('content_static')->where('ID', 'twitter-link')->get())
            ->with('nav_card_left_image', DB::table('content_static')->where('ID', 'nav-card-left-image')->get())
            ->with('nav_card_center_image', DB::table('content_static')->where('ID', 'nav-card-center-image')->get())
            ->with('nav_card_right_image', DB::table('content_static')->where('ID', 'nav-card-right-image')->get())
            ->with('stories_card_1_image', DB::table('content_static')->where('ID', 'stories-card-1-image')->get())
            ->with('stories_card_2_image', DB::table('content_static')->where('ID', 'stories-card-2-image')->get())
            ->with('stories_card_3_image', DB::table('content_static')->where('ID', 'stories-card-3-image')->get())
            ->with('stories_card_4_image', DB::table('content_static')->where('ID', 'stories-card-4-image')->get())
            ->with('EXPLORE_OFFERINGS', DB::select('SELECT * FROM explore_our_offering order by dataCreate asc limit 8;'))
        ->with('CUSTOMERS_SAY', DB::select('SELECT * FROM customers_say order by dataCreate asc limit 5;'));

    }
}
